version: "3.7"
services:
    # image project
    todo-list:
        build: 
            args: 
                user: jpls
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-todo
        container_name: php_todo
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
          - mysql
        networks: 
            - todo
    
    # nginx
    nginx:
        image: nginx:alpine
        container_name: nginx_todo
        restart: unless-stopped
        ports: 
            - 8010:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - todo

    # db mysql
    mysql:
        image: mysql:5.7.22
        container_name: mysql_todo
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: curso_php_pdo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3392:3306
        networks: 
            - todo

networks: 
    todo:
        driver: bridge